platform :ios, '9.0'

target 'SDKTrackDemo' do

   pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git'
  
   pod 'MBProgressHUD'
   
   pod 'WBAdsTrackSDK', '~> 1.0.1'

end
